# Stage 1: Build
FROM maven:3.8.3-openjdk-17-slim AS build
WORKDIR /app

# Копируем только pom.xml для загрузки зависимостей
COPY pom.xml .

# Загружаем зависимости (создаем кэшируемый слой)
RUN mvn dependency:go-offline

# Копируем исходный код
COPY src ./src

# Собираем проект с многопоточной сборкой
RUN mvn clean package -DskipTests -T 4

# Stage 2: Production
FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]